### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by steverob** [codetribe/ruby_links#4]
Is it running on SQLite on digital ocean? If so we should switch to a standard db like postgres. and We could use postgres full text search.. it can come in handy for us given we need to search across links, titles and description.

**Comment by kannandoss** [comment]
PG only.....

**Comment by steverob** [comment]
Thats great :+1:

**Comment by steverob** [comment]
Okay. We can use pg_search then.

**Comment by kannandoss** [comment]
update in development mode also...... 
confirm once with Boss....

**Comment by mindaslab** [comment]
ok no problem.
